### ISSUE TITLE
Crashes when trying to load Zim-file

### ISSUE THREAD

**Issue by xvitaly** [kiwix/kiwix-desktop#443]
Kiwix Desktop 2.0.1 crashes when trying to load `wikipedia_ru_all_maxi_2020-04.zim` due to unhandled exception:

```$ kiwix-desktop 
Library directory : "/home/user/.local/share/kiwix"
add widget
terminate called after throwing an instance of 'std::runtime_error'
  what():  error 2 opening file "
Aborted (core dumped)
```

OS: Fedora 32.
Kiwix Desktop from repositories.

Download URL:
```
https://download.kiwix.org/zim/wikipedia_ru_all_maxi.zim
```

**Comment by xvitaly** [comment]
Backtrace of crash:

```
#0  0x00007fffeeed2a25 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007fffeeebb895 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007fffef11b961 in __gnu_cxx::__verbose_terminate_handler() [clone .cold] ()
   from /lib64/libstdc++.so.6
No symbol table info available.
#3  0x00007fffef12742c in __cxxabiv1::__terminate(void (*)()) ()
   from /lib64/libstdc++.so.6
No symbol table info available.
#4  0x00007fffef127497 in std::terminate() () from /lib64/libstdc++.so.6
No symbol table info available.
#5  0x00007fffef127749 in __cxa_throw () from /lib64/libstdc++.so.6
No symbol table info available.
#6  0x00007fffee92ffdb in zim::FileCompound::FileCompound(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold] ()
   from /lib64/libzim.so.6
No symbol table info available.
#7  0x00007fffee941416 in zim::FileImpl::FileImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib64/libzim.so.6
No symbol table info available.
#8  0x00007fffee93d3a6 in zim::File::File(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib64/libzim.so.6
No symbol table info available.
#9  0x00007ffff7ec14e2 in kiwix::Reader::Reader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /lib64/libkiwix.so.9
No symbol table info available.
#10 0x00007ffff7e8f483 in kiwix::Library::getReaderById(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold] ()
   from /lib64/libkiwix.so.9
No symbol table info available.
#11 0x0000555555583ef7 in Library::getReader(QString const&) ()
No symbol table info available.
#12 0x000055555558ad48 in WebView::onUrlChanged(QUrl const&) ()
No symbol table info available.
#13 0x00007fffef4ffa60 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /lib64/libQt5Core.so.5
No symbol table info available.
#14 0x00007ffff7e53ba5 in QWebEngineView::urlChanged(QUrl const&) ()
   from /lib64/libQt5WebEngineWidgets.so.5
No symbol table info available.
#15 0x00007fffef4ffa60 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /lib64/libQt5Core.so.5
No symbol table info available.
#16 0x00007ffff7e479f5 in QWebEnginePage::urlChanged(QUrl const&) ()
   from /lib64/libQt5WebEngineWidgets.so.5
No symbol table info available.
#17 0x00007ffff0e6cea8 in QtWebEngineCore::WebContentsDelegateQt::NavigationStateChanged(content::WebContents*, content::InvalidateTypes) () from /lib64/libQt5WebEngineCore.so.5
No symbol table info available.
#18 0x00007ffff0e6794f in QtWebEngineCore::WebContentsAdapter::load(QWebEngineHttpRequest const&) () from /lib64/libQt5WebEngineCore.so.5
No symbol table info available.
#19 0x00007ffff0e67e11 in QtWebEngineCore::WebContentsAdapter::load(QUrl const&) ()
   from /lib64/libQt5WebEngineCore.so.5
No symbol table info available.
#20 0x000055555557f2a0 in KiwixApp::openZimFile(QString const&) ()
No symbol table info available.
#21 0x000055555557f518 in QtPrivate::QFunctorSlotObject<KiwixApp::createAction()::{lambda()#2}, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
No symbol table info available.
#22 0x00007fffef4ffa60 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /lib64/libQt5Core.so.5
No symbol table info available.
#23 0x00007fffeff85456 in QAction::triggered(bool) () from /lib64/libQt5Widgets.so.5
No symbol table info available.
#24 0x00007fffeff87d70 in QAction::activate(QAction::ActionEvent) ()
   from /lib64/libQt5Widgets.so.5
No symbol table info available.
#25 0x00007ffff007cd82 in QAbstractButtonPrivate::click() ()
   from /lib64/libQt5Widgets.so.5
No symbol table info available.
#26 0x00007ffff007cea5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /lib64/libQt5Widgets.so.5
No symbol table info available.
#27 0x00007ffff016dcbe in QToolButton::mouseReleaseEvent(QMouseEvent*) ()
   from /lib64/libQt5Widgets.so.5
No symbol table info available.
#28 0x00007fffeffce208 in QWidget::event(QEvent*) () from /lib64/libQt5Widgets.so.5
No symbol table info available.
#29 0x00007fffeff8be76 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /lib64/libQt5Widgets.so.5
No symbol table info available.
#30 0x00007fffeff93671 in QApplication::notify(QObject*, QEvent*) ()
   from /lib64/libQt5Widgets.so.5
No symbol table info available.
#31 0x00007fffef4d98a0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /lib64/libQt5Core.so.5
No symbol table info available.
#32 0x00007fffeff9256a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from /lib64/libQt5Widgets.so.5
No symbol table info available.
#33 0x00007fffeffe7732 in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
   from /lib64/libQt5Widgets.so.5
No symbol table info available.
#34 0x00007fffeffea69e in QWidgetWindow::event(QEvent*) () from /lib64/libQt5Widgets.so.5
No symbol table info available.
#35 0x00007fffeff8be76 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /lib64/libQt5Widgets.so.5
No symbol table info available.
#36 0x00007fffef4d98a0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /lib64/libQt5Core.so.5
No symbol table info available.
#37 0x00007fffefa3ba6b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib64/libQt5Gui.so.5
No symbol table info available.
#38 0x00007fffefa1f5bb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Gui.so.5
No symbol table info available.
#39 0x00007fffdcd51d8e in xcbSourceDispatch(_GSource*, int (*)(void*), void*) ()
   from /lib64/libQt5XcbQpa.so.5
No symbol table info available.
#40 0x00007fffeae907cf in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
No symbol table info available.
#41 0x00007fffeae90b58 in g_main_context_iterate.constprop ()
   from /lib64/libglib-2.0.so.0
No symbol table info available.
#42 0x00007fffeae90c23 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
No symbol table info available.
#43 0x00007fffef524c06 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
No symbol table info available.
#44 0x00007fffef4d821b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /lib64/libQt5Core.so.5
No symbol table info available.
#45 0x00007fffef4dfdf6 in QCoreApplication::exec() () from /lib64/libQt5Core.so.5
No symbol table info available.
#46 0x0000555555579f76 in main ()
No symbol table info available.
```

**Comment by kelson42** [comment]
@xvitaly What is the md5sum of your local file?

**Comment by kelson42** [comment]
@xvitaly I have tested and it works fine for me. Which seems to confirm your local file is corrupted. That said Kiwix-Desktop should not crash. It would be helpful if you could upload your (probably broken) ZIM file somewhere, so I can download it.

**Comment by xvitaly** [comment]
@kelson42 Thanks. I will re-download Zim file again and check.

**Comment by kelson42** [comment]
@xvitaly could you please keep and upload the broken file somewhere?

**Comment by xvitaly** [comment]
> could you please keep and upload the broken file somewhere?

24 GB?

**Comment by kelson42** [comment]
@xvitaly Yes, all the file if you can.

**Comment by xvitaly** [comment]
> Yes, all the file if you can.

Sorry, this is impossible with my Internet connection. Upload speed is very limited by ISP.

I re-downloaded the file again using BitTorrent protocol and now everything works fine. Thank you.
