### ISSUE TITLE
 Kiwix always crashing after exit on Ubuntu

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#514]
With my own compilation of kiwix-desktop with Ubuntu 20.04 (but the PPA version crashes as well):
```
$ ./kiwix-desktop 
Library directory : "/home/kelson/.local/share/kiwix"
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
aria2 tellActive failed : Invalid return code from ariaaria2 tellWaiting failed : Invalid return code from ariaadd widget
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid return code from aria
Aborted (core dumped)
kelson@camber:~/code/kiwix-desktop$ gdb ./kiwix-desktop 
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./kiwix-desktop...
(No debugging symbols found in ./kiwix-desktop)
(gdb) run
Starting program: /home/kelson/code/kiwix-desktop/kiwix-desktop 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe3080700 (LWP 755434)]
[New Thread 0x7fffe1c4f700 (LWP 755435)]
[New Thread 0x7fffe144e700 (LWP 755436)]
[New Thread 0x7fffd3235700 (LWP 755437)]
[New Thread 0x7fffd2a34700 (LWP 755438)]
[New Thread 0x7fffd2233700 (LWP 755439)]
[New Thread 0x7fffd1a32700 (LWP 755440)]
[New Thread 0x7fffc397c700 (LWP 755441)]
[Detaching after fork from child process 755442]
[Detaching after fork from child process 755443]
[New Thread 0x7fffc317b700 (LWP 755446)]
[New Thread 0x7fffc297a700 (LWP 755447)]
[New Thread 0x7fffc2179700 (LWP 755448)]
[New Thread 0x7fffc1978700 (LWP 755449)]
[New Thread 0x7fffc1177700 (LWP 755450)]
[New Thread 0x7fffc0976700 (LWP 755451)]
[New Thread 0x7fff9ffff700 (LWP 755452)]
[New Thread 0x7fff9f7fe700 (LWP 755453)]
[New Thread 0x7fff9effd700 (LWP 755454)]
[New Thread 0x7fff9e7fc700 (LWP 755455)]
[New Thread 0x7fff9dffb700 (LWP 755456)]
[New Thread 0x7fff9d7fa700 (LWP 755457)]
[New Thread 0x7fff9cdf3700 (LWP 755458)]
[New Thread 0x7fff7ffff700 (LWP 755459)]
[New Thread 0x7fff7f7fe700 (LWP 755460)]
Library directory : "/home/kelson/.local/share/kiwix"
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
[Detaching after fork from child process 755461]
[New Thread 0x7fff7effd700 (LWP 755462)]
[New Thread 0x7fff7e7fc700 (LWP 755463)]
[Thread 0x7fff7e7fc700 (LWP 755463) exited]
aria2 tellActive failed : Invalid return code from ariaaria2 tellWaiting failed : Invalid return code from aria[New Thread 0x7fff7e7fc700 (LWP 755464)]
[New Thread 0x7fff7dffb700 (LWP 755465)]
[New Thread 0x7fff7d7fa700 (LWP 755466)]
[New Thread 0x7fff7cff9700 (LWP 755480)]
add widget
[New Thread 0x7fff57fff700 (LWP 755481)]
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid return code from aria

Thread 1 "kiwix-desktop" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffef868859 in __GI_abort () at abort.c:79
#2  0x00007fffefaf0951 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fffefafc47c in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fffefafb459 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fffefafbe11 in __gxx_personality_v0 () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fffefa47bef in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007fffefa485aa in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x00007ffff7eaadca in kiwix::Aria2::saveSession (this=0x555555e6d690) at ../src/aria2.cpp:233
#9  0x00007ffff7ea9858 in kiwix::Aria2::close (this=0x555555e6d690) at ../src/aria2.cpp:123
#10 0x00007ffff7e7e024 in kiwix::Downloader::close (this=0x555555ef5030) at ../src/downloader.cpp:155
#11 0x0000555555591841 in KiwixApp::~KiwixApp() ()
#12 0x000055555557f227 in main ()
```

**Comment by kelson42** [comment]
The problem was because of a strange self-compiled old version of libaria2
